version: 1.0.0.{build}

platform: x64

branches:
  only:
    - master

clone_folder: c:\gopath\src\github.com\AidosKuneen/aidosd

environment:
  GOPATH: c:\gopath
  FILE_NAME: aidosd_$(appveyor_repo_tag_name)_win_amd64

install:
  - set Path=%Path%;C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin\
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - go get -d ./...

build_script:
 - go build -o adkd.exe -ldflags "-X github.com/AidosKuneen/aidosd/Version=\"$(appveyor_repo_tag_name)\""
 - 7z a %FILE_NAME%.zip adkd.exe aidosd.conf
  - dir

test_script:
  - go tool vet -all .
  - go test ./... -v  -timeout 15m

artifacts:
  - path: .\$(FILE_NAME).zip
    name: binary

deploy:
  release: $(appveyor_repo_tag_name)
  description: ''
  provider: GitHub
  auth_token:
    secure: iN3vpbgZkGndynDF8/2YbXxENoBrGlQOUvJ7yJrVN5DXA4QrFpREYJVa+xlgLJFT
  artifact: binary # This is the name we specified in the artifacts section.
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true 